# Generated by Django 4.2.1 on 2024-02-20 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follower'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
