# Generated by Django 4.2.1 on 2024-02-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='numberFollowers',
            field=models.IntegerField(default='0'),
        ),
    ]
