# Generated by Django 4.2.1 on 2024-02-20 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_follower_numberfollowers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='follower',
            new_name='user',
        ),
    ]
