# Generated by Django 4.2.1 on 2024-02-20 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_rename_follower_follower_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follower',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_followings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follower',
            name='numberFollowings',
            field=models.IntegerField(default=0),
        ),
    ]
