# Generated by Django 4.2.1 on 2024-02-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_follower_followers_follower_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='numberFollowers',
            field=models.IntegerField(default=1),
        ),
    ]
