# Generated by Django 4.2.1 on 2024-02-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_follower_numberfollowers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_followers', to='network.post'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_followings', to='network.post'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='numberFollowers',
            field=models.IntegerField(default=0),
        ),
    ]
