# Generated by Django 4.2.1 on 2024-02-21 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_remove_follower_followers_remove_follower_following_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='user',
        ),
    ]
