# Generated by Django 4.2.1 on 2024-02-21 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_countfollow_follow_delete_follower_countfollow_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countfollow',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='count', to=settings.AUTH_USER_MODEL),
        ),
    ]
