# Generated by Django 4.2.1 on 2024-02-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_alter_follower_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='following',
        ),
        migrations.AddField(
            model_name='follower',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_followers', to='network.follower'),
        ),
        migrations.AddField(
            model_name='follower',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_followings', to='network.follower'),
        ),
    ]
