# Generated by Django 4.2.1 on 2024-02-21 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_alter_countfollow_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='numberFollowers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='follow',
            name='numberFollowings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='follow',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_followers', to='network.follow'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_followings', to='network.follow'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CountFollow',
        ),
    ]
