# Generated by Django 4.2.1 on 2024-02-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_remove_follower_followers_remove_follower_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='user_followers', to='network.follower'),
        ),
        migrations.AlterField(
            model_name='follower',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='user_followings', to='network.follower'),
        ),
    ]
