# Generated by Django 4.2.1 on 2024-02-21 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_alter_follower_followers_alter_follower_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='user_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='user_followings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='numberFollowers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='numberFollowings',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
