# Generated by Django 4.2.1 on 2024-02-21 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_alter_follow_followers_alter_follow_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
