# Generated by Django 4.2.1 on 2024-02-22 12:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_remove_user_followers_remove_user_following_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostFollowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts', models.ManyToManyField(related_name='postsOfUserFollowed', to='network.post')),
                ('user', models.ManyToManyField(related_name='followedUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
