# Generated by Django 4.2.1 on 2024-02-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=1),
        ),
    ]
