# Generated by Django 4.2.1 on 2024-02-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0024_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
