# Generated by Django 4.2.1 on 2024-02-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_post_liked_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='unliked',
            field=models.BooleanField(default=False),
        ),
    ]
