# Generated by Django 4.2.1 on 2024-02-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0026_post_unliked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='unliked',
        ),
    ]
