# Generated by Django 4.2.1 on 2024-02-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0027_remove_post_unliked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostFollowers',
        ),
    ]
